name: Job Crawler and Email Notification

on:
  schedule:
    # 每天北京时间早上8点运行
    - cron: '30 15 * * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PWD: ${{ secrets.EMAIL_PWD }}

jobs:
  crawl-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Run job crawler
      run: python job_crawler.py
      
    - name: Upload Excel file as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: job_data
        path: job_data.xlsx
