name: Job Crawler
on:
  schedule:
    - cron: '30 15 * * *'  # UTC时间9点运行（北京时间23:30点）
  workflow_dispatch:  # 支持手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas fake-useragent python-dateutil openpyxl requests
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      
      - name: Run crawler
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: |
          python crawler_github.py
      
      # 上传爬取结果作为构建产物
      - name: Upload job data
        uses: actions/upload-artifact@v4
        with:
          name: job-data
          path: |
            job_data.json
            job_data.xlsx
            users.json
            user_data/
      
      # 提交数据变更
      - name: Commit and push changes
        run: |
          git add job_data.json job_data.xlsx users.json user_data/*
          git commit -m "自动更新: 招聘数据 $(date +'%Y-%m-%d %H:%M')" || echo "没有变更可提交"
          git push
