name: Job Crawler

on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间0点运行（北京时间8点）
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 重要！允许推送回仓库
        fetch-depth: 0  # 获取完整历史记录

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        # 确保chromium路径正确
        sudo ln -s /usr/bin/chromium-browser /usr/bin/chromium
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.9.0 fake-useragent==1.1.3 pandas==1.5.3 openpyxl==3.0.10 python-dotenv==0.21.0

    - name: Run crawler
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 用于提交更改
      run: |
        python main.py
        
        # 配置Git用户信息
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # 检查是否有文件变更
        if git diff --quiet; then
          echo "没有数据变更，无需提交"
        else
          # 提交变更
          git add job_data.json job_data.xlsx crawler_stats.json
          git commit -m "自动更新招聘数据 $(date +'%Y-%m-%d %H:%M:%S')"
          git push
          echo "数据变更已提交到仓库"
        fi

    - name: Upload artifacts
      if: always()  # 即使失败也上传
      uses: actions/upload-artifact@v4
      with:
        name: job-data
        path: |
          job_data.json
          job_data.xlsx
          crawler_stats.json
