name: Daily Job Crawler

on:
  schedule:
    - cron: '30 15 * * *'  # 每天UTC时间20:00运行（北京时间凌晨4:00）
  workflow_dispatch:      # 支持手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    # 设置环境变量
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
      
      - name: Install Python dependencies
        run: |
          pip install selenium pandas fake_useragent openpyxl
      
      - name: Run crawler
        run: |
          # 设置正确的无头浏览器路径
          export PATH=$PATH:/usr/bin/chromium-browser
          
          # 运行爬虫脚本
          python crawler_github.py
